"""add_bot_conversation_states

Revision ID: 27a1dd4d0ad8
Revises: ded704c7466a
Create Date: 2026-07-01 19:47:45.747211

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '27a1dd4d0ad8'
down_revision: Union[str, Sequence[str], None] = 'ded704c7466a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('channel_configurations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('channel_id', sa.UUID(), nullable=False),
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('is_encrypted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_channel_configurations_channel_id'), 'channel_configurations', ['channel_id'], unique=False)
    op.create_index(op.f('ix_channel_configurations_id'), 'channel_configurations', ['id'], unique=False)
    op.create_index(op.f('ix_channel_configurations_key'), 'channel_configurations', ['key'], unique=False)
    op.create_table('channel_credentials',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('channel_id', sa.UUID(), nullable=False),
    sa.Column('credential_type', sa.String(length=100), nullable=False),
    sa.Column('encrypted_value', sa.Text(), nullable=False),
    sa.Column('iv', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_channel_credentials_channel_id'), 'channel_credentials', ['channel_id'], unique=False)
    op.create_index(op.f('ix_channel_credentials_credential_type'), 'channel_credentials', ['credential_type'], unique=False)
    op.create_index(op.f('ix_channel_credentials_id'), 'channel_credentials', ['id'], unique=False)
    op.create_table('channel_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('channel_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('external_message_id', sa.String(length=255), nullable=True),
    sa.Column('direction', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('message_type', sa.String(length=50), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('media_url', sa.String(length=500), nullable=True),
    sa.Column('media_type', sa.String(length=100), nullable=True),
    sa.Column('template_name', sa.String(length=255), nullable=True),
    sa.Column('phone_number', sa.String(length=50), nullable=True),
    sa.Column('email_address', sa.String(length=255), nullable=True),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('extra_metadata', sa.JSON(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('delivered_at', sa.DateTime(), nullable=True),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_channel_messages_channel_id'), 'channel_messages', ['channel_id'], unique=False)
    op.create_index(op.f('ix_channel_messages_company_id'), 'channel_messages', ['company_id'], unique=False)
    op.create_index(op.f('ix_channel_messages_external_message_id'), 'channel_messages', ['external_message_id'], unique=False)
    op.create_index(op.f('ix_channel_messages_id'), 'channel_messages', ['id'], unique=False)
    op.create_index(op.f('ix_channel_messages_phone_number'), 'channel_messages', ['phone_number'], unique=False)
    op.create_table('channel_webhook_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('channel_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('headers', sa.JSON(), nullable=True),
    sa.Column('processing_status', sa.String(length=50), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('received_at', sa.DateTime(), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_channel_webhook_logs_channel_id'), 'channel_webhook_logs', ['channel_id'], unique=False)
    op.create_index(op.f('ix_channel_webhook_logs_company_id'), 'channel_webhook_logs', ['company_id'], unique=False)
    op.create_index(op.f('ix_channel_webhook_logs_event_type'), 'channel_webhook_logs', ['event_type'], unique=False)
    op.create_index(op.f('ix_channel_webhook_logs_id'), 'channel_webhook_logs', ['id'], unique=False)
    op.create_table('bot_conversation_states',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('phone_number', sa.String(length=50), nullable=False),
    sa.Column('scenario_id', sa.UUID(), nullable=False),
    sa.Column('current_step', sa.Integer(), nullable=False),
    sa.Column('collected_data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scenario_id'], ['bot_scenarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bot_conversation_states_company_id'), 'bot_conversation_states', ['company_id'], unique=False)
    op.create_index(op.f('ix_bot_conversation_states_id'), 'bot_conversation_states', ['id'], unique=False)
    op.create_index(op.f('ix_bot_conversation_states_phone_number'), 'bot_conversation_states', ['phone_number'], unique=False)
    op.drop_column('channels', 'configuration')
    op.create_index('ix_conversations_status_company_id', 'conversations', ['status', 'company_id'], unique=False)
    op.create_index('ix_customers_phone_number_company_id', 'customers', ['phone_number', 'company_id'], unique=False)
    op.create_index('ix_knowledge_base_category_company_id', 'knowledge_base', ['category_id', 'company_id'], unique=False)
    op.alter_column('users', 'company_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'company_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_index('ix_knowledge_base_category_company_id', table_name='knowledge_base')
    op.drop_index('ix_customers_phone_number_company_id', table_name='customers')
    op.drop_index('ix_conversations_status_company_id', table_name='conversations')
    op.add_column('channels', sa.Column('configuration', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_bot_conversation_states_phone_number'), table_name='bot_conversation_states')
    op.drop_index(op.f('ix_bot_conversation_states_id'), table_name='bot_conversation_states')
    op.drop_index(op.f('ix_bot_conversation_states_company_id'), table_name='bot_conversation_states')
    op.drop_table('bot_conversation_states')
    op.drop_index(op.f('ix_channel_webhook_logs_id'), table_name='channel_webhook_logs')
    op.drop_index(op.f('ix_channel_webhook_logs_event_type'), table_name='channel_webhook_logs')
    op.drop_index(op.f('ix_channel_webhook_logs_company_id'), table_name='channel_webhook_logs')
    op.drop_index(op.f('ix_channel_webhook_logs_channel_id'), table_name='channel_webhook_logs')
    op.drop_table('channel_webhook_logs')
    op.drop_index(op.f('ix_channel_messages_phone_number'), table_name='channel_messages')
    op.drop_index(op.f('ix_channel_messages_id'), table_name='channel_messages')
    op.drop_index(op.f('ix_channel_messages_external_message_id'), table_name='channel_messages')
    op.drop_index(op.f('ix_channel_messages_company_id'), table_name='channel_messages')
    op.drop_index(op.f('ix_channel_messages_channel_id'), table_name='channel_messages')
    op.drop_table('channel_messages')
    op.drop_index(op.f('ix_channel_credentials_id'), table_name='channel_credentials')
    op.drop_index(op.f('ix_channel_credentials_credential_type'), table_name='channel_credentials')
    op.drop_index(op.f('ix_channel_credentials_channel_id'), table_name='channel_credentials')
    op.drop_table('channel_credentials')
    op.drop_index(op.f('ix_channel_configurations_key'), table_name='channel_configurations')
    op.drop_index(op.f('ix_channel_configurations_id'), table_name='channel_configurations')
    op.drop_index(op.f('ix_channel_configurations_channel_id'), table_name='channel_configurations')
    op.drop_table('channel_configurations')
    # ### end Alembic commands ###
