"""Add bot configuration models

Revision ID: 40d23a25d6d9
Revises: ac39eb9b77a4
Create Date: 2026-06-30 12:03:42.106366

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40d23a25d6d9'
down_revision: Union[str, Sequence[str], None] = 'ac39eb9b77a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bot_configurations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('bot_type', sa.Enum('NATIVE', 'ML', 'HYBRID', name='bottype'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('welcome_message', sa.Text(), nullable=True),
    sa.Column('away_message', sa.Text(), nullable=True),
    sa.Column('closing_message', sa.Text(), nullable=True),
    sa.Column('unknown_message', sa.Text(), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('native_rules', sa.JSON(), nullable=True),
    sa.Column('ml_enabled', sa.Boolean(), nullable=False),
    sa.Column('ml_provider', sa.String(length=50), nullable=True),
    sa.Column('ml_model', sa.String(length=100), nullable=True),
    sa.Column('ml_temperature', sa.String(length=10), nullable=True),
    sa.Column('ml_max_tokens', sa.Integer(), nullable=True),
    sa.Column('fallback_strategy', sa.String(length=50), nullable=True),
    sa.Column('confidence_threshold', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bot_configurations_company_id'), 'bot_configurations', ['company_id'], unique=False)
    op.create_index(op.f('ix_bot_configurations_id'), 'bot_configurations', ['id'], unique=False)
    op.create_table('bot_keywords',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('bot_configuration_id', sa.UUID(), nullable=False),
    sa.Column('keyword', sa.String(length=255), nullable=False),
    sa.Column('response', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['bot_configuration_id'], ['bot_configurations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bot_keywords_bot_configuration_id'), 'bot_keywords', ['bot_configuration_id'], unique=False)
    op.create_index(op.f('ix_bot_keywords_id'), 'bot_keywords', ['id'], unique=False)
    op.create_index(op.f('ix_bot_keywords_keyword'), 'bot_keywords', ['keyword'], unique=False)
    op.create_table('bot_scenarios',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('bot_configuration_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('trigger_keyword', sa.String(length=255), nullable=False),
    sa.Column('steps', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['bot_configuration_id'], ['bot_configurations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bot_scenarios_bot_configuration_id'), 'bot_scenarios', ['bot_configuration_id'], unique=False)
    op.create_index(op.f('ix_bot_scenarios_id'), 'bot_scenarios', ['id'], unique=False)
    op.create_index(op.f('ix_bot_scenarios_trigger_keyword'), 'bot_scenarios', ['trigger_keyword'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bot_scenarios_trigger_keyword'), table_name='bot_scenarios')
    op.drop_index(op.f('ix_bot_scenarios_id'), table_name='bot_scenarios')
    op.drop_index(op.f('ix_bot_scenarios_bot_configuration_id'), table_name='bot_scenarios')
    op.drop_table('bot_scenarios')
    op.drop_index(op.f('ix_bot_keywords_keyword'), table_name='bot_keywords')
    op.drop_index(op.f('ix_bot_keywords_id'), table_name='bot_keywords')
    op.drop_index(op.f('ix_bot_keywords_bot_configuration_id'), table_name='bot_keywords')
    op.drop_table('bot_keywords')
    op.drop_index(op.f('ix_bot_configurations_id'), table_name='bot_configurations')
    op.drop_index(op.f('ix_bot_configurations_company_id'), table_name='bot_configurations')
    op.drop_table('bot_configurations')
    # ### end Alembic commands ###
