"""Add MLModel and update bot configuration ML fields

Revision ID: ded704c7466a
Revises: a82c470f58bf
Create Date: 2026-06-30 12:24:21.510964

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ded704c7466a'
down_revision: Union[str, Sequence[str], None] = 'a82c470f58bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Create ml_models table first (this will create the ENUM types mlprovider and mlmodeltype)
    op.create_table('ml_models',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('model_type', sa.Enum('RAG', 'CLASSIFIER', 'RERANKER', name='mlmodeltype'), nullable=False),
    sa.Column('provider', sa.Enum('OPENAI', 'ANTHROPIC', 'OLLAMA', name='mlprovider'), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=True),
    sa.Column('configuration', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ml_models_company_id'), 'ml_models', ['company_id'], unique=False)
    op.create_index(op.f('ix_ml_models_id'), 'ml_models', ['id'], unique=False)
    
    # Create fallbackstrategy ENUM type
    op.execute("CREATE TYPE fallbackstrategy AS ENUM ('ML_TO_NATIVE', 'NATIVE_TO_ML', 'PARALLEL')")
    
    # Convert existing columns to ENUM types using raw SQL
    op.execute("ALTER TABLE bot_configurations ALTER COLUMN ml_provider TYPE mlprovider USING ml_provider::text::mlprovider")
    op.execute("ALTER TABLE bot_configurations ALTER COLUMN fallback_strategy TYPE fallbackstrategy USING fallback_strategy::text::fallbackstrategy")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Convert columns back to VARCHAR
    op.execute("ALTER TABLE bot_configurations ALTER COLUMN fallback_strategy TYPE VARCHAR(50)")
    op.execute("ALTER TABLE bot_configurations ALTER COLUMN ml_provider TYPE VARCHAR(50)")
    
    # Drop table
    op.drop_index(op.f('ix_ml_models_id'), table_name='ml_models')
    op.drop_index(op.f('ix_ml_models_company_id'), table_name='ml_models')
    op.drop_table('ml_models')
    
    # Drop fallbackstrategy ENUM type
    op.execute("DROP TYPE IF EXISTS fallbackstrategy")
    # ### end Alembic commands ###
